spring:
  profiles:
    active: prod
  application:
    name: nt-tianyan
  datasource:
    db_sct_vip:
      url: jdbc:mysql://172.16.0.25:3306/db_sct_vip?useUnicode=true&amp;characterEncoding=UTF-8&amp;useFastDateParsing=false
      username: zhuoren
      password: zhuoren3553!
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: false
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 1800000
    db_lion:
      url: jdbc:mysql://172.16.0.23:3307/db_lion?useUnicode=true&amp;characterEncoding=UTF-8&amp;useFastDateParsing=false
      username: wanglu
      password: Wanglu_running1500!
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: false
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 1800000

#Spring eureka配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 配置
baseUrl: https://api.cyhz.com/v2/
tianyan:
  pubVolume:
    url: http://www.baidu.com
    cron: 0 25 16 * * ?

#Logging 配置
logging:
  file: /data/logs/Microserivces/${spring.application.name}.log
  level:
    cn.newtouch.tianyan: INFO
    cn.newtouch.tianyan.dao.sctvip: INFO
    cn.newtouch.tianyan.dao.lion: INFO

server:
  context-path: /
  port: 20024