# 大库 DB
spring:
  datasource:
    db_lion:
      url: jdbc:mysql://172.16.0.23:3307/db_lion?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&useSSL=false
      username: kanlulin
      password: Ljfyun01
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: false
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 1800000